# Generated by Django 3.2.7 on 2021-09-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotBeanCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
            ],
        ),
    ]
