"""
Django settings for django_huey_test project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

from redis import ConnectionPool


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rzxioi9w!zd_6oo7w8%#vl2093g_rd-g#k@a3%43&^iiz)!u+t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'huey.contrib.djhuey',
    'django_huey',
    'django_extensions',
    'polls',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_huey_test.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_huey_test.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('POSTGRES_DB', 'huey'),
        'USER': os.environ.get('POSTGRES_USER', 'huey'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'huey'),
        'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


pool = ConnectionPool(
    host='redis',
    port=6379,
    max_connections=100
)

huey_consumer_options = {
    'workers': 12,
    'worker_type': 'thread',
    'initial_delay': 0.1,  # Smallest polling interval, same as -d.
    'backoff': 1.15,  # Exponential backoff using this rate, -b.
    'max_delay': 10.0,  # Max possible polling interval, -m.
    'scheduler_interval': 1,  # Check schedule every second, -s.
    'periodic': True,  # Enable crontab feature.
    'check_worker_health': True,  # Enable worker health checks.
    'health_check_interval': 1,  # Check worker health every second.
}

huey_queue_options = {
    'huey_class': 'huey.RedisHuey',  # Huey implementation to use.
    'name': 'app',  # Use db name for huey.
    'results': True,  # Store return values of tasks.
    'store_none': False,  # If a task returns None, do not save to results.
    'immediate': False,
    'utc': False,  # Use local time for all times internally.
    'blocking': True,  # Perform blocking pop rather than poll Redis.
    'connection': {
        'connection_pool': pool,
        # huey-specific connection parameters.
        'read_timeout': 1,  # If not polling (blocking pop), use timeout.
    },
    'consumer': huey_consumer_options
}

# HUEY = huey_queue_options

DJANGO_HUEY = {
    'default': 'default',
    'queues': {
        'default': {
            **huey_queue_options,
            'name': 'default_tasks',
        },
        'process': {
            **huey_queue_options,
            'name': 'process_tasks',
            'consumer': {
                **huey_consumer_options,
                'worker_type': 'process'
            }
        }
    }
}
